<?php
	DEFINED("JOBBAGS_FIELDNAMES_WITH_CUSTOMER_INFO") or DEFINE("JOBBAGS_FIELDNAMES_WITH_CUSTOMER_INFO",
		"qmi1.ID as JOB_ID ,QM_TITLE, QM_JOB_NUM, QM_JOB_QTY,QM_REQD_DATE,QM_DLY_DATE,QM_ADD_DATE,QM_CUST_CODE,RM_NAME");
	DEFINED("WITH_CUSTOMER_INFO") or DEFINE("WITH_CUSTOMER_INFO","LEFT JOIN rmi1 ON rm_cust=qm_cust_code");

?>