export const CALENDAR_PAGE_ADD_SCHEDULE_TO       = 'CALENDAR_PAGE_ADD_SCHEDULE_TO';
export const CALENDAR_PAGE_ADD_SCHEDULE_TO_ERROR = 'CALENDAR_PAGE_ADD_SCHEDULE_TO_ERROR';
export const CALENDAR_PAGE_REFRESH               = 'CALENDAR_PAGE_REFRESH';

export const MANAGE_JOB_ADD_NEW                  = 'MANAGE_JOB_ADD_NEW';
