// FOR CALENDAR_PAGE SECTION
export const CALENDAR_PAGE_ADD_SCHEDULE_TO        = 'CALENDAR_PAGE_ADD_SCHEDULE_TO';
export const CALENDAR_PAGE_ADD_RECURRING_TO_DATE  = 'CALENDAR_PAGE_ADD_RECURRING_TO_DATE';
export const CALENDAR_PAGE_CHANGE_DAYS            = 'CALENDAR_PAGE_CHANGE_DAYS';
export const CALENDAR_PAGE_CHANGE_GET_JOBS        = 'CALENDAR_PAGE_CHANGE_GET_JOBS';
export const CALENDAR_PAGE_MOVE_DEP_SIDE_BY_SIDE  = 'CALENDAR_PAGE_MOVE_DEP_SIDE_BY_SIDE';
export const CALENDAR_PAGE_MOVE_DEP_SBS_UPDATE_DB = 'CALENDAR_PAGE_MOVE_DEP_SBS_UPDATE_DB';
export const CALENDAR_PAGE_REFRESH                = 'CALENDAR_PAGE_REFRESH';
export const CALENDAR_VIEW_DAY_SET_CALENDAR_DATE  = 'CALENDAR_VIEW_DAY_SET_CALENDAR_DATE';
export const CALENDAR_PAGE_VIEW_DATE_GET_JOBS     = 'CALENDAR_PAGE_VIEW_DATE_GET_JOBS';
export const CALENDAR_MAIN_PAGE_REFRESH           = ' CALENDAR_MAIN_PAGE_REFRESH';

// FOR MANAGE_JOB SECTION
export const MANAGE_JOB_ADD_NEW_EDIT              = 'MANAGE_JOB_ADD_NEW_EDIT';
export const MANAGE_JOB_UPDATE_VIEWS              = 'MANAGE_JOB_UPDATE_VIEWS';

// FOR MY TASKS SECTION
export const MANAGE_TASKS_ACTION                  = 'MANAGE_TASKS_ACTION';

// FOR USER SETTINGS SECTION
export const USER_SETTINGS_SAVE                   = 'USER_SETTINGS_SAVE';

// FOR SCHEDULING SETTINGS SECTION
export const ST_SETTINGS_SAVE                     = 'ST_SETTINGS_SAVE';

// GLOBAL CONSTANT
export const RESET_ALL_ACTION                     = 'RESET_ALL_ACTION';
export const IS_WORKING                           = 'IS_WORKING';


