export const CALENDAR_PAGE_ADD_SCHEDULE_TO        = 'CALENDAR_PAGE_ADD_SCHEDULE_TO';
export const CALENDAR_PAGE_CHANGE_DAYS            = 'CALENDAR_PAGE_CHANGE_DAYS';
export const CALENDAR_PAGE_CHANGE_GET_JOBS        = 'CALENDAR_PAGE_CHANGE_GET_JOBS';
export const CALENDAR_PAGE_REFRESH                = 'CALENDAR_PAGE_REFRESH';

export const MANAGE_JOB_ADD_NEW                   = 'MANAGE_JOB_ADD_NEW';
